version: '3'

services:   
    product-services:
        build: ./server
        volumes:
            - ./server:/usr/src/app
        ports:
            - "5000:5000"    
    website:
        build: ./website
        volumes:
            - ./website:/usr/src/app
        ports:
            - "5001:5000"
        depends_on:
            - product-services